### ISSUE TITLE
Duplicate images

### ISSUE THREAD

**Issue by pedrobbarbosa** [iamatulsingh/pinterest-image-scrap#1]
![65b12116-4e07-42e5-9031-946b740baefe](https://user-images.githubusercontent.com/44590774/128602411-c317d241-2056-4b6a-9657-846e253f4bb1.jpeg)

It looks like some images that were downloaded are being duplicated in my file folder. This is starting to become an issue as I periodically download images from Pinterest, and it's starting to take up a lot of space.

**Comment by iamatulsingh** [comment]
Thanks for opening issue. I'll be working on it.

**Comment by iamatulsingh** [comment]
New code is pushed for fixing this issue
