### ISSUE TITLE
download

### ISSUE THREAD

**Issue by badriyatus123** [iamatulsingh/pinterest-image-scrap#2]
not all photos are downloaded
![gambar](https://user-images.githubusercontent.com/87899416/130967882-214c0cde-9b59-470b-abbe-e945cb92d707.png)

**Comment by iamatulsingh** [comment]
Sorry, I'll be required more information about this issue. Please explain this issue.

**Comment by iamatulsingh** [comment]
That issue is fixed that's why I'm closing this issue. Please repoen it if you still facing this issue.
@badriyatus123
