### ISSUE TITLE
more results?

### ISSUE THREAD

**Issue by batrlatom** [iamatulsingh/pinterest-image-scrap#5]
Hi, 
I am getting about 150 results from the keyword "ring" . Is there any easy way to make it 1000+ ?

**Comment by iamatulsingh** [comment]
It depends on the search results. If that return more results, image count
will be high. In this library, I'm just scraping images that is easily
available without doing any reverse engineering.

**Comment by batrlatom** [comment]
thanks for the response, at the en, I just realized that I can get another results by using different queries .. like 'rings', 'wdding rings', etc.
